export type MoodId = 
  | 'joy'
  | 'serenity'
  | 'sad'
  | 'awful'
  | 'anxious'
  | 'hope'
  | 'gratitude'
  | 'love'
  | 'wonder'
  | 'contemplation'
  | 'strength'
  | 'melancholy'
  | 'healing';

export interface MoodConfig {
  id: MoodId;
  name: string;
  label: string;
  color: string; // hex
  secondaryColor: string;
  glowColor: string;
  bgGradient: string;
  iconName: string;
  description: string;
  element: 'fire' | 'water' | 'air' | 'earth' | 'ether';
  frequency: number; // Hz for sound resonance
}

export interface VoiceNoteData {
  audioUrl?: string; // base64 or blob URL
  duration: number; // in seconds
  waveform?: number[];
  recordedAt: string;
}

export interface MemoryMedia {
  id: string;
  type: 'image' | 'video';
  url: string;
  name?: string;
  caption?: string;
}

export interface MemoryStar {
  id: string;
  title: string;
  content: string;
  date: string; // ISO string
  mood: MoodId;
  moodIntensity: number; // 1 to 5
  tags: string[];
  photos: string[]; // URLs / data URLs
  videos: string[]; // URLs / data URLs
  voiceNote?: VoiceNoteData;
  location?: string;
  weather?: string;
  isFavorite?: boolean;
  
  // 3D/2D Celestial coordinates
  x: number; // -1000 to +1000 or canvas coords
  y: number; // -1000 to +1000
  z?: number; // depth
  size?: number;
  twinklePhase?: number;
  starType?: 'radiant' | 'nova' | 'pulsar' | 'cluster' | 'binary';
  connectedConstellationIds?: string[];
}

export interface Constellation {
  id: string;
  name: string;
  description: string;
  moodTheme?: MoodId | 'eclectic';
  starIds: string[];
  edges: [string, string][]; // Pairs of star IDs to draw lines between
  color: string;
  glowColor: string;
  mythology?: string;
  isAutoGenerated?: boolean;
  createdAt: string;
}

export interface WellnessActivity {
  id: string;
  category: 'music' | 'walk' | 'friend' | 'memory' | 'break' | 'breathe';
  title: string;
  subtitle: string;
  description: string;
  durationMinutes?: number;
  icon: string;
  color: string;
  accent: string;
}
