import React, { useState } from 'react';
import { X, Sparkles } from 'lucide-react';
import { Constellation, MoodId, MemoryStar } from '../types/journal';
import { getMood } from '../utils/moods';

interface SaveConstellationModalProps {
  isOpen: boolean;
  onClose: () => void;
  selectedStarIds: string[];
  memories: MemoryStar[];
  onSave: (constellation: Omit<Constellation, 'id' | 'createdAt'>) => void;
}

export function SaveConstellationModal({
  isOpen,
  onClose,
  selectedStarIds,
  onSave,
}: SaveConstellationModalProps) {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [mythology, setMythology] = useState('');
  const [selectedMood, setSelectedMood] = useState<MoodId>('joy');

  if (!isOpen) return null;

  const moodConfig = getMood(selectedMood);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || selectedStarIds.length < 2) return;

    // Build sequential edges [star0-star1, star1-star2, etc.]
    const edges: [string, string][] = [];
    for (let i = 0; i < selectedStarIds.length - 1; i++) {
      edges.push([selectedStarIds[i], selectedStarIds[i + 1]]);
    }
    if (selectedStarIds.length >= 4) {
      edges.push([selectedStarIds[selectedStarIds.length - 1], selectedStarIds[0]]);
    }

    onSave({
      name: name.trim(),
      description: description.trim() || `A celestial bond woven across ${selectedStarIds.length} memories.`,
      mythology: mythology.trim() || 'A beacon of shared reflections guiding the path forward.',
      moodTheme: selectedMood,
      starIds: selectedStarIds,
      edges,
      color: moodConfig.color,
      glowColor: moodConfig.glowColor,
      isAutoGenerated: false,
    });

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md">
      <div className="relative w-full max-w-lg rounded-3xl border border-[#eed09d]/30 bg-[#080c18]/95 shadow-[0_0_60px_rgba(0,0,0,0.9)] p-7 sm:p-8 text-slate-100 animate-in fade-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="flex items-start justify-between pb-4 border-b border-slate-800/80">
          <div>
            <span className="text-[10px] uppercase tracking-widest font-serif text-[#eed09d] flex items-center gap-1.5 mb-1">
              <Sparkles className="w-3 h-3" />
              constellation inscription
            </span>
            <h2 className="text-xl font-serif font-normal text-[#fdfaf3] lowercase">
              name your constellation
            </h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-full text-slate-400 hover:text-white hover:bg-slate-800/80 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="mt-5 space-y-4">
          <div className="p-3 bg-slate-950/60 rounded-2xl border border-slate-800/80 text-xs font-serif text-slate-300">
            weaving <span className="text-[#eed09d] font-semibold">{selectedStarIds.length} stars</span> across your sky.
          </div>

          <div>
            <label className="block text-[11px] font-serif text-[#eed09d] mb-1.5 italic">
              constellation name:
            </label>
            <input
              type="text"
              required
              placeholder="e.g. Corona Aeterna, The Wanderer"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full rounded-2xl bg-slate-950/70 border border-slate-700/80 px-4 py-2.5 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-[#eed09d]/80"
            />
          </div>

          <div>
            <label className="block text-[11px] font-serif text-[#eed09d] mb-1.5 italic">
              theme mood:
            </label>
            <div className="grid grid-cols-6 gap-1.5">
              {['joy', 'serenity', 'sad', 'awful', 'anxious', 'hope'].map((m) => {
                const conf = getMood(m as MoodId);
                const isCur = selectedMood === m;
                return (
                  <button
                    key={m}
                    type="button"
                    onClick={() => setSelectedMood(m as MoodId)}
                    className={`flex flex-col items-center justify-center gap-1 p-2 rounded-xl border text-xs transition cursor-pointer font-serif min-w-0 ${
                      isCur
                        ? 'border-[#eed09d] bg-slate-800 text-white font-medium shadow-sm'
                        : 'border-slate-800 bg-slate-950/60 text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    <span className="w-2.5 h-2.5 rounded-full shrink-0" style={{ backgroundColor: conf.color }} />
                    <span className="truncate min-w-0 text-[10px]">{conf.name}</span>
                  </button>
                );
              })}
            </div>
          </div>

          <div>
            <label className="block text-[11px] font-serif text-[#eed09d] mb-1.5 italic">
              meaning / story:
            </label>
            <textarea
              rows={2}
              placeholder="What unites these memories together?"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full rounded-2xl bg-slate-950/70 border border-slate-700/80 px-4 py-2 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-[#eed09d]/80 resize-none"
            />
          </div>

          <div>
            <label className="block text-[11px] font-serif text-[#eed09d] mb-1.5 italic">
              mythology / wisdom inscription:
            </label>
            <input
              type="text"
              placeholder="e.g. A celestial beacon of shared light"
              value={mythology}
              onChange={(e) => setMythology(e.target.value)}
              className="w-full rounded-2xl bg-slate-950/70 border border-slate-700/80 px-4 py-2 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-[#eed09d]/80"
            />
          </div>

          <div className="pt-2">
            <button
              type="submit"
              disabled={!name.trim()}
              className="w-full py-2.5 px-6 rounded-full bg-[#faedd9] hover:bg-[#ffffff] disabled:opacity-40 text-[#0f1424] font-serif font-medium text-xs tracking-wider transition cursor-pointer shadow-md"
            >
              save your constellation
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
