import { MoodConfig, MoodId } from '../types/journal';

export const MOODS: Record<MoodId, MoodConfig> = {
  joy: {
    id: 'joy',
    name: 'Joy',
    label: 'Joy & Happiness',
    color: '#FFB800',
    secondaryColor: '#FFD700',
    glowColor: 'rgba(255, 184, 0, 0.65)',
    bgGradient: 'from-amber-500/20 to-yellow-500/5',
    iconName: 'Sun',
    description: 'Vibrant, uplifting starlight and happiness',
    element: 'fire',
    frequency: 528,
  },
  serenity: {
    id: 'serenity',
    name: 'Peaceful',
    label: 'Calm & Serene',
    color: '#38BDF8',
    secondaryColor: '#7DD3FC',
    glowColor: 'rgba(56, 189, 248, 0.65)',
    bgGradient: 'from-sky-500/20 to-cyan-500/5',
    iconName: 'Waves',
    description: 'Tranquil calm, stillness, and ease',
    element: 'water',
    frequency: 432,
  },
  sad: {
    id: 'sad',
    name: 'Sad',
    label: 'Sad & Melancholy',
    color: '#64748B',
    secondaryColor: '#94A3B8',
    glowColor: 'rgba(100, 116, 139, 0.65)',
    bgGradient: 'from-slate-600/20 to-slate-900/10',
    iconName: 'CloudRain',
    description: 'Gentle sorrow, heartache, and tender processing',
    element: 'water',
    frequency: 174,
  },
  awful: {
    id: 'awful',
    name: 'Awful',
    label: 'Awful & Distressed',
    color: '#E11D48',
    secondaryColor: '#FB7185',
    glowColor: 'rgba(225, 29, 72, 0.65)',
    bgGradient: 'from-rose-700/20 to-red-950/10',
    iconName: 'Flame',
    description: 'Heavy, overwhelmed, or painful moments',
    element: 'fire',
    frequency: 210,
  },
  anxious: {
    id: 'anxious',
    name: 'Anxious',
    label: 'Anxious & Overthinking',
    color: '#A855F7',
    secondaryColor: '#C084FC',
    glowColor: 'rgba(168, 85, 247, 0.65)',
    bgGradient: 'from-purple-600/20 to-indigo-900/10',
    iconName: 'Compass',
    description: 'Restlessness, tension, and nervous thoughts',
    element: 'air',
    frequency: 396,
  },
  hope: {
    id: 'hope',
    name: 'Hope',
    label: 'Hope & Rebirth',
    color: '#2DD4BF',
    secondaryColor: '#99F6E4',
    glowColor: 'rgba(45, 212, 191, 0.65)',
    bgGradient: 'from-teal-500/20 to-emerald-500/5',
    iconName: 'Sparkles',
    description: 'A gentle dawn promising light ahead',
    element: 'air',
    frequency: 417,
  },
  gratitude: {
    id: 'gratitude',
    name: 'Gratitude',
    label: 'Gratitude & Abundance',
    color: '#F59E0B',
    secondaryColor: '#FDE68A',
    glowColor: 'rgba(245, 158, 11, 0.65)',
    bgGradient: 'from-amber-600/20 to-orange-500/5',
    iconName: 'Sparkles',
    description: 'Deep appreciation for life’s quiet wonders',
    element: 'earth',
    frequency: 639,
  },
  love: {
    id: 'love',
    name: 'Love',
    label: 'Love & Affection',
    color: '#FB7185',
    secondaryColor: '#FECDD3',
    glowColor: 'rgba(251, 113, 133, 0.65)',
    bgGradient: 'from-rose-500/20 to-pink-500/5',
    iconName: 'Heart',
    description: 'Tender warmth, bond, and heartfelt devotion',
    element: 'water',
    frequency: 528,
  },
  wonder: {
    id: 'wonder',
    name: 'Wonder',
    label: 'Wonder & Awe',
    color: '#C084FC',
    secondaryColor: '#E9D5FF',
    glowColor: 'rgba(192, 132, 252, 0.65)',
    bgGradient: 'from-purple-500/20 to-indigo-500/5',
    iconName: 'Compass',
    description: 'Curiosity, magic, and boundless imagination',
    element: 'air',
    frequency: 741,
  },
  contemplation: {
    id: 'contemplation',
    name: 'Thoughtful',
    label: 'Contemplation & Insight',
    color: '#818CF8',
    secondaryColor: '#C7D2FE',
    glowColor: 'rgba(129, 140, 248, 0.65)',
    bgGradient: 'from-indigo-500/20 to-slate-500/5',
    iconName: 'Moon',
    description: 'Deep thought, quiet reflection, and philosophical musing',
    element: 'ether',
    frequency: 852,
  },
  healing: {
    id: 'healing',
    name: 'Healing',
    label: 'Healing & Growth',
    color: '#34D399',
    secondaryColor: '#A7F3D0',
    glowColor: 'rgba(52, 211, 153, 0.65)',
    bgGradient: 'from-emerald-500/20 to-green-500/5',
    iconName: 'Leaf',
    description: 'Restoration, nurturing self-care, and renewal',
    element: 'earth',
    frequency: 396,
  },
  strength: {
    id: 'strength',
    name: 'Strength',
    label: 'Strength & Courage',
    color: '#F43F5E',
    secondaryColor: '#FDA4AF',
    glowColor: 'rgba(244, 63, 94, 0.65)',
    bgGradient: 'from-rose-600/20 to-orange-500/5',
    iconName: 'Shield',
    description: 'Inner resilience, perseverance, and bravery',
    element: 'fire',
    frequency: 963,
  },
  melancholy: {
    id: 'melancholy',
    name: 'Sad',
    label: 'Sad & Melancholy',
    color: '#64748B',
    secondaryColor: '#94A3B8',
    glowColor: 'rgba(100, 116, 139, 0.65)',
    bgGradient: 'from-slate-500/20 to-blue-900/10',
    iconName: 'CloudRain',
    description: 'Quiet sorrow, emotional release, and gentle processing',
    element: 'water',
    frequency: 174,
  },
};

export const BASIC_MOOD_LIST: MoodConfig[] = [
  MOODS.joy,
  MOODS.serenity,
  MOODS.sad,
  MOODS.awful,
  MOODS.anxious,
  MOODS.hope,
];

export const MOOD_LIST = BASIC_MOOD_LIST;

export function getMood(id: MoodId | string): MoodConfig {
  if (id === 'melancholy') return MOODS.sad;
  return (MOODS as Record<string, MoodConfig>)[id] || MOODS.joy;
}
